export default function AIEditorPage() {
	// {
	// 	label: "Explore",
	// 	href: "/explore",
	// 	icon: Compass,
	// },
	// {
	// 	label: "Project Rules",
	// 	href: "/project-rules",
	// 	icon: BookText,
	// },
	// {
	// 	label: "Project MCP",
	// 	href: "/mcp",
	// 	icon: Plug,
	// },

	//
	// Convert this to a Bun App with Server-Sent-Events and Websockets.
	// Use a database and MCP instead of a file-storage to increase performance.

	// Features
	// Notes
	// Labels
	// - Bug / New Feature / Improvement
	// Tasks
	// - Backlog, Planned, In Progress, Completed / Cancelled
	// Cycles

	// Templates

	// MCP Servers

	// Conventional Commits

	// Notepads
	// Project Rules

	// MCP support (use it as an MCP server)

	// Ollama support (tasks generated by Claude and Perplexity right now)

	// Two way task/PRD sync

	// Generate test file for any task file to easily verify functionality and improve code stability as Cursor implements other tasks

	// Bulk verify implementation and mark all related tasks as done — makes it easier to drop this into an existing project

	return <div>AI Editor</div>;
}
