export default function AIEditorPage() {
	// <h3 className="text-lg font-semibold">User Rules</h3>
	// <div></div>

	// <h3 className="text-lg font-semibold">Project Rules</h3>
	// <div></div>

	// * Labels
	// - This is for developer's reference
	// * Milestones
	// 1. Create an MVP
	// 2. Add support for multiple users
	// 3. Create PRD for each milestone
	// * Tasks
	// - Blocking, Blocked By
	// - Bug / New Feature / Improvement
	// - Backlog, Planned, In Progress, Completed / Cancelled
	// * Cycles
	// Suggest Features

	// Ollama support (tasks generated by Claude and Perplexity right now)

	// Two way task/PRD sync
	// Generate test file for any task file to easily verify functionality and improve code stability as Cursor implements other tasks
	// Bulk verify implementation and mark all related tasks as done — makes it easier to drop this into an existing project

	return <div>AI</div>;
}
